dbVenta-cnx: Server=localhost,1801;Database=dbVenta;Uid=sa;pwd=MSqwert@159;Encrypt=false
url-base-servicio-stock: https://localhost:7065
log-mongo-server-db: mongodb://127.0.0.1:27017/dbLog
log-mongo-db-collection: logs-Ventas
